var obj = JSON.parse($response.body);
    obj.isVip= "2;
obj.vipType= "2";
obj.singleType= null;
obj.vipEndTime= 31";
obj.  vipInfos=  "1"}];
obj.studyGuide= "1";
obj.isVip= 2;
obj.mockTotal= 100;
obj.trainTotal= 100;
    $done({body: JSON.stringify(obj)});
